@256                 D=A
@0                   M=D
@1                   M=D
@2                   M=D
@3                   M=D
@4                   M=D
@256                 D=A
@0                   M=D
@300                 D=A
@1                   M=D
@400                 D=A
@2                   M=D
@3000                D=A
@3                   M=D
@3010                D=A
@4                   M=D
@10                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@0                   D=A
@1                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@21                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@22                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@2                   D=A
@2                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@1                   D=A
@2                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@36                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@6                   D=A
@3                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@42                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@45                  D=A
@0                   M=M+1
                     A=M-1
                     M=D
@5                   D=A
@4                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@2                   D=A
@4                   D=D+M
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@510                 D=A
@0                   M=M+1
                     A=M-1
                     M=D
@6                   D=A
@5                   D=D+A
@15                  M=D
@0                   M=M-1
                     A=M
                     D=M
@15                  A=M
                     M=D
@0                   D=A
@1                   A=D+M
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@5                   D=A
@4                   A=D+M
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@0                   M=M-1
                     A=M
                     D=M
                     A=A-1
                     M=D+M
@1                   D=A
@2                   A=D+M
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@0                   M=M-1
                     A=M
                     D=M
                     A=A-1
                     M=M-D
@6                   D=A
@3                   A=D+M
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@6                   D=A
@3                   A=D+M
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@0                   M=M-1
                     A=M
                     D=M
                     A=A-1
                     M=D+M
@0                   M=M-1
                     A=M
                     D=M
                     A=A-1
                     M=M-D
@6                   D=A
@5                   A=D+A
                     D=M
@0                   M=M+1
                     A=M-1
                     M=D
@0                   M=M-1
                     A=M
                     D=M
                     A=A-1
                     M=D+M
